language: bash
sudo: required

script: 
    -  sudo apt-get update
    -  sudo apt-get install unzip scons wine winetricks python-pip xvfb x11-xkb-utils xfonts-100dpi xfonts-75dpi xfonts-scalable xfonts-cyrillic x11-app -y
    -  winetricks allfonts
    -  bash ./build_win32.sh chess3.py
